# Generated by Django 5.2.8 on 2025-12-17 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_appointment_assigned_technician"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_reminded",
                    models.BooleanField(default=False, verbose_name="Đã nhắc khách"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú nhắc hẹn")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_log",
                        to="bookings.appointment",
                        verbose_name="Lịch hẹn",
                    ),
                ),
                (
                    "reminded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người nhắc",
                    ),
                ),
            ],
        ),
    ]
