# Generated by Django 5.2.8 on 2026-02-07 06:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_alter_customer_fanpage"),
        ("sales", "0006_service_commission_rate"),
        ("service_calendar", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminderlog",
            name="appointment",
        ),
        migrations.RemoveField(
            model_name="reminderlog",
            name="is_reminded",
        ),
        migrations.RemoveField(
            model_name="reminderlog",
            name="note",
        ),
        migrations.RemoveField(
            model_name="reminderlog",
            name="reminded_by",
        ),
        migrations.AddField(
            model_name="reminderlog",
            name="assigned_staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reminderlog",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reminderlog",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reminderlog",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="reminderlog",
            name="customer_phone_backup",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="reminderlog",
            name="reminder_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 7, 6, 43, 51, 460047, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reminderlog",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
        migrations.CreateModel(
            name="TreatmentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian làm"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú buổi làm")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                        verbose_name="Khách hàng",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bác sĩ phụ trách",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.order",
                        verbose_name="Thuộc đơn hàng",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.service",
                        verbose_name="Dịch vụ thực hiện",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_as_tech",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="KTV chính",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buổi điều trị (Tour)",
                "verbose_name_plural": "Lịch sử Tour KTV",
                "ordering": ["-session_date"],
            },
        ),
    ]
