# Generated by Django 5.2.8 on 2025-11-24 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=200, verbose_name='Tên liệu trình/Sản phẩm')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Tổng tiền (VNĐ)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú thêm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo đơn')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.appointment', verbose_name='Từ lịch hẹn nào')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Khách hàng')),
                ('sale_consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sale chốt đơn')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Doanh thu & Đơn hàng',
            },
        ),
    ]
