# Generated by Django 5.2.8 on 2025-11-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dịch vụ/Liệu trình')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Giá niêm yết (VNĐ)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Dịch vụ & Bảng giá',
                'verbose_name_plural': 'Quản lý Dịch vụ',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Thực thu (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='treatment_name',
            field=models.CharField(max_length=200, verbose_name='Tên liệu trình chốt'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.service', verbose_name='Dịch vụ chọn'),
        ),
    ]
