# Generated by Django 5.2.8 on 2025-12-12 09:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_appointment_assigned_technician"),
        ("sales", "0002_service_alter_order_total_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-order_date"],
                "verbose_name": "Đơn hàng",
                "verbose_name_plural": "Đơn hàng và Hợp đồng",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "verbose_name": "Dịch vụ",
                "verbose_name_plural": "Danh sách Dịch vụ",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="sale_consultant",
        ),
        migrations.RemoveField(
            model_name="order",
            name="treatment_name",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="actual_revenue",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=10,
                verbose_name="Thực thu (VND)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="assigned_consultant",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "CONSULTANT"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tư vấn viên (Sales)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Ngày chốt đơn"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="original_price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, verbose_name="Giá gốc"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="base_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=10,
                verbose_name="Giá cố định (VND)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.appointment",
                verbose_name="Lịch hẹn liên quan",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(
                default=False, verbose_name="Đã thanh toán (Hoàn thành)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, verbose_name="Ghi chú đơn hàng"),
        ),
        migrations.AlterField(
            model_name="order",
            name="service",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="sales.service",
                verbose_name="Dịch vụ chính",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=10,
                verbose_name="Tổng giá trị đơn hàng",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Tên dịch vụ"
            ),
        ),
    ]
