# Generated by Django 5.2.8 on 2026-01-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_order_options_alter_service_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="debt_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, verbose_name="Còn nợ"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="actual_revenue",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=10,
                verbose_name="Thực thu (Đã trả)",
            ),
        ),
    ]
