# Generated by Django 5.2.8 on 2026-01-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_order_debt_amount_alter_order_actual_revenue"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Tiền mặt"),
                    ("TRANSFER", "Chuyển khoản"),
                    ("CARD", "Quẹt thẻ"),
                    ("INSTALLMENT", "Trả góp"),
                ],
                default="TRANSFER",
                max_length=20,
                verbose_name="Hình thức thanh toán",
            ),
        ),
    ]
