# Generated by Django 5.2.8 on 2026-02-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Nhập số % (Ví dụ: 0.5, 1, 3, 5)",
                max_digits=5,
                verbose_name="% Hoa hồng KTV",
            ),
        ),
    ]
