# Generated by Django 5.2.8 on 2026-02-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_service_commission_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_sessions",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Số buổi khách mua thực tế (VD: 10 buổi)",
                verbose_name="Tổng số buổi liệu trình",
            ),
        ),
    ]
