# Generated by Django 5.2.8 on 2026-03-24 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_order_total_sessions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="digitals",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role__in": ["ADMIN", "MARKETING"]},
                related_name="digital_assigned_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Digital Marketing",
            ),
        ),
    ]
