# Generated by Django 5.2.8 on 2026-07-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_order_order_date_index"),
        ("sales", "0008_order_digitals"),
    ]

    operations = []
