# Generated by Django 5.2.8 on 2025-11-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ và Tên')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Tuổi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('skin_condition', models.CharField(choices=[('ACNE', 'Mụn viêm/Mụn ẩn'), ('PIGMENTATION', 'Nám/Tàn nhang'), ('SCAR', 'Sẹo rỗ'), ('AGING', 'Lão hóa/Nếp nhăn'), ('OTHER', 'Khác')], default='OTHER', max_length=50, verbose_name='Vấn đề về da')),
                ('note_telesale', models.TextField(blank=True, verbose_name='Ghi chú ban đầu (Telesale)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Danh sách Khách hàng',
            },
        ),
    ]
