# Generated by Django 5.2.8 on 2025-11-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tỉnh/Thành phố'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook Ads'), ('GOOGLE', 'Google Ads'), ('SEO', 'SEO Website'), ('TIKTOK', 'Tiktok'), ('REFERRAL', 'Bạn giới thiệu'), ('OTHER', 'Khác')], default='FACEBOOK', max_length=20, verbose_name='Nguồn khách'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ chi tiết'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note_telesale',
            field=models.TextField(blank=True, verbose_name='Ghi chú ban đầu'),
        ),
    ]
