# Generated by Django 5.2.8 on 2025-11-27 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_age_customer_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Danh sách Khách hàng'},
        ),
        migrations.AddField(
            model_name='customer',
            name='ranking',
            field=models.CharField(choices=[('MEMBER', 'Thành viên'), ('SILVER', 'Bạc'), ('GOLD', 'Vàng'), ('DIAMOND', 'Kim Cương')], default='MEMBER', max_length=20, verbose_name='Hạng thành viên'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
    ]
