# Generated by Django 4.2.26 on 2025-12-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_options_customer_ranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='skin_condition',
            field=models.CharField(choices=[('ULTHERAPY', 'Ultherapy'), ('THERMA', 'Therma'), ('PRP', 'PRP'), ('VAGINAL_REJUVENATION', 'Trẻ hoá vùng kín'), ('HAIR_REMOVAL', 'Triệt lông'), ('FAT_REDUCTION', 'Giảm béo'), ('LASER', 'Laser'), ('OTHER', 'Khác')], default='OTHER', max_length=50, verbose_name='Dịch vụ quan tâm'),
        ),
    ]
