# Generated by Django 4.2.26 on 2025-12-01 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0005_alter_customer_skin_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_telesale',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TELESALE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Telesale phụ trách'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Nữ'), ('MALE', 'Nam'), ('UNKNOWN', 'Không rõ')], default='FEMALE', max_length=10, verbose_name='Giới tính'),
        ),
    ]
