# Generated by Django 4.2.26 on 2025-12-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_assigned_telesale_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã khách hàng/ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fanpage',
            field=models.CharField(blank=True, choices=[('BS_QUAN', 'Bác sĩ Cao Trần Quân'), ('VMEDICAL_CLINIC', 'V - Medical Clinic'), ('DL_VMEDICAL', 'Phòng Khám Da Liễu Thẩm Mỹ V-Medical'), ('QUAN_SINCE_2006', 'Cao Trần Quân - Viện Da Liễu V Medical since 2006'), ('ULTHERAPY_57A', 'Ultherapy Prime - Căng Da Không Phẫu Thuật 57A Trần Quốc Thảo'), ('OTHER', 'Khác / Không rõ')], max_length=50, null=True, verbose_name='Fanpage Nguồn'),
        ),
    ]
