# Generated by Django 5.2.8 on 2025-12-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_customer_customer_code_customer_fanpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="skin_condition",
            field=models.CharField(
                choices=[
                    ("PROFHILO", "Profhilo"),
                    ("EXOSONE", "Exosone"),
                    ("REJURAN", "Rejuran"),
                    ("KARISMA", "Karisma"),
                    ("HAIR_TREATMENT", "Tóc"),
                    ("ULTHERAPY", "Ultherapy"),
                    ("THERMA", "Therma"),
                    ("PRP", "PRP"),
                    ("VAGINAL_REJUVENATION", "Trẻ hoá vùng kín"),
                    ("HAIR_REMOVAL", "Triệt lông"),
                    ("FAT_REDUCTION", "Giảm béo"),
                    ("LASER", "Laser"),
                    ("OTHER", "Khác"),
                ],
                default="OTHER",
                max_length=50,
                verbose_name="Dịch vụ quan tâm",
            ),
        ),
    ]
