# Generated by Django 5.2.8 on 2025-12-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_alter_customer_skin_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="fanpage",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "CC_KIM_CUONG_SG_HV",
                        "Căng chỉ kim cương Sài Gòn - Bác sĩ Hoàng Vũ",
                    ),
                    (
                        "ULTRA_DIAMOND_DB_HV",
                        "Nâng cơ trẻ hoá Ultra Diamond - Bác sĩ Danh Bảo Hoàng Vũ",
                    ),
                    ("BS_QUAN", "Bác sĩ Cao Trần Quân"),
                    ("VMEDICAL_CLINIC", "V - Medical Clinic"),
                    ("DL_VMEDICAL", "Phòng Khám Da Liễu Thẩm Mỹ V-Medical"),
                    (
                        "QUAN_SINCE_2006",
                        "Cao Trần Quân - Viện Da Liễu V Medical since 2006",
                    ),
                    (
                        "ULTHERAPY_57A",
                        "Ultherapy Prime - Căng Da Không Phẫu Thuật 57A Trần Quốc Thảo",
                    ),
                    ("OTHER", "Khác / Không rõ"),
                ],
                max_length=50,
                null=True,
                verbose_name="Fanpage Nguồn",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="skin_condition",
            field=models.CharField(
                choices=[
                    ("THREAD_LIFT", "Căng chỉ"),
                    ("PROFHILO", "Profhilo"),
                    ("EXOSONE", "Exosone"),
                    ("REJURAN", "Rejuran"),
                    ("KARISMA", "Karisma"),
                    ("HAIR_TREATMENT", "Tóc"),
                    ("ULTHERAPY", "Ultherapy"),
                    ("THERMA", "Therma"),
                    ("PRP", "PRP"),
                    ("VAGINAL_REJUVENATION", "Trẻ hoá vùng kín"),
                    ("HAIR_REMOVAL", "Triệt lông"),
                    ("FAT_REDUCTION", "Giảm béo"),
                    ("LASER", "Laser"),
                    ("OTHER", "Khác"),
                ],
                default="OTHER",
                max_length=50,
                verbose_name="Dịch vụ quan tâm",
            ),
        ),
    ]
