# Generated by Django 5.2.8 on 2026-03-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_alter_customer_fanpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="fanpage",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "CC_KIM_CUONG_SG_HV",
                        "Căng chỉ kim cương Sài Gòn - Bác sĩ Hoàng Vũ",
                    ),
                    (
                        "ULTRA_DIAMOND_DB_HV",
                        "Nâng cơ trẻ hoá Ultra Diamond - Bác sĩ Danh Bảo Hoàng Vũ",
                    ),
                    ("BS_HOANG_VU", "Bác Sĩ Hoàng Vũ - CK I Da Liễu"),
                    ("HOANG_VU", "Bác sĩ CKI Hoàng Vũ - Viện da liễu V Medical"),
                    ("BS_QUAN", "Cao Trần Quân - Viện Da Liễu V Medical"),
                    ("QUAN_SINCE_2006", "Bác sĩ Cao Trần Quân - V Medical Clinic"),
                    ("VMEDICAL_CLINIC", "V - Medical Clinic"),
                    ("DL_VMEDICAL", "Phòng Khám Da Liễu Thẩm Mỹ V-Medical"),
                    (
                        "ULTHERAPY_57A",
                        "Ultherapy Prime - Căng Da Không Phẫu Thuật 57A Trần Quốc Thảo",
                    ),
                    ("OTHER", "Khác / Không rõ"),
                    ("VMEDICAL_PK_DL", "V Medical - Phòng khám da liễu thẩm mỹ"),
                    (
                        "PK_VMEDICAL_TM",
                        "Phòng Khám V Medical - Thẩm Mỹ Da Công Nghệ Cao",
                    ),
                ],
                max_length=50,
                null=True,
                verbose_name="Fanpage Nguồn",
            ),
        ),
    ]
