# Generated by Django 5.2.8 on 2026-03-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_alter_customer_fanpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fanpage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã Fanpage"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Tên Fanpage hiển thị"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fanpage",
                "verbose_name_plural": "Danh sách Fanpage",
            },
        ),
        migrations.AlterField(
            model_name="customer",
            name="fanpage",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "CC_KIM_CUONG_SG_HV",
                        "Căng chỉ kim cương Sài Gòn - Bác sĩ Hoàng Vũ",
                    ),
                    (
                        "ULTRA_DIAMOND_DB_HV",
                        "Nâng cơ trẻ hoá Ultra Diamond - Bác sĩ Danh Bảo Hoàng Vũ",
                    ),
                    ("BS_HOANG_VU", "Bác Sĩ Hoàng Vũ - CK I Da Liễu"),
                    ("HOANG_VU", "Bác sĩ CKI Hoàng Vũ - Viện da liễu V Medical"),
                    ("BS_QUAN", "Cao Trần Quân - Viện Da Liễu V Medical"),
                    ("QUAN_SINCE_2006", "Bác sĩ Cao Trần Quân - V Medical Clinic"),
                    ("VMEDICAL_CLINIC", "V - Medical Clinic"),
                    ("DL_VMEDICAL", "Phòng Khám Da Liễu Thẩm Mỹ V-Medical"),
                    (
                        "ULTHERAPY_57A",
                        "Ultherapy Prime - Căng Da Không Phẫu Thuật 57A Trần Quốc Thảo",
                    ),
                    ("OTHER", "Khác / Không rõ"),
                    ("VMEDICAL_PK_DL", "V Medical - Phòng khám da liễu thẩm mỹ"),
                    (
                        "PK_VMEDICAL_TM",
                        "Phòng Khám V Medical - Thẩm Mỹ Da Công Nghệ Cao",
                    ),
                ],
                max_length=50,
                null=True,
                verbose_name="Fanpage Nguồn (Cũ)",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="fanpages",
            field=models.ManyToManyField(
                blank=True, to="customers.fanpage", verbose_name="Các Fanpage Nguồn"
            ),
        ),
    ]
