# Generated by Django 5.2.8 on 2026-03-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0013_fanpage_alter_customer_fanpage_customer_fanpages"),
    ]

    operations = [
        migrations.AddField(
            model_name="fanpage",
            name="assigned_marketer",
            field=models.CharField(
                blank=True,
                help_text="Nhập chính xác tên (VD: Vũ, Hưng, Huy, Long) để hệ thống tự cộng doanh số",
                max_length=100,
                null=True,
                verbose_name="Marketer phụ trách",
            ),
        ),
    ]
