# Generated by Django 5.2.8 on 2026-03-24 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0014_fanpage_assigned_marketer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="fanpage",
            name="assigned_marketer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["ADMIN", "MARKETING"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_fanpages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Marketer phụ trách",
            ),
        ),
    ]
