# Generated by Django 5.2.8 on 2026-03-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0016_alter_fanpage_assigned_marketer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="fb_lead_id",
            field=models.CharField(
                blank=True,
                help_text="ID khách hàng tiềm năng đổ về từ Facebook",
                max_length=100,
                null=True,
                verbose_name="Facebook Lead ID",
            ),
        ),
    ]
