# Generated by Django 5.2.8 on 2026-03-31 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên Fanpage")),
                (
                    "page_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Page ID"
                    ),
                ),
                ("access_token", models.TextField(verbose_name="Page Access Token")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Kích hoạt"),
                ),
                (
                    "allowed_staff",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nhân viên được quyền đăng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cấu hình Fanpage",
                "verbose_name_plural": "Cấu hình Fanpage",
            },
        ),
    ]
