# Generated by Django 5.2.8 on 2026-03-31 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_marketing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookPostLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Nội dung")),
                (
                    "status",
                    models.CharField(
                        choices=[("Success", "Thành công"), ("Failed", "Thất bại")],
                        max_length=20,
                    ),
                ),
                ("post_id", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời điểm đăng"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facebook_marketing.facebookpage",
                        verbose_name="Fanpage",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nhân viên thực hiện",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký đăng bài",
                "ordering": ["-created_at"],
            },
        ),
    ]
