# Generated by Django 5.2.8 on 2025-12-04 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Tên tài liệu"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MACHINE", "Máy móc & Công nghệ"),
                            ("PROTOCOL", "Phác đồ điều trị"),
                            ("SERVICE", "Dịch vụ lâm sàng"),
                            ("INTERNAL_TRAINING", "Đào tạo nội bộ"),
                        ],
                        default="MACHINE",
                        max_length=50,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Link Ảnh minh họa",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tên file HTML nội dung",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="Mô tả ngắn"),
                ),
                (
                    "pass_score",
                    models.IntegerField(default=80, verbose_name="Điểm đạt (%)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tài liệu đào tạo",
                "verbose_name_plural": "Kho Tài liệu",
            },
        ),
        migrations.CreateModel(
            name="TrainingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Nội dung câu hỏi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="resources.productdocument",
                        verbose_name="Tài liệu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Câu hỏi trắc nghiệm",
                "verbose_name_plural": "Kho Câu hỏi",
            },
        ),
        migrations.CreateModel(
            name="TrainingChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(max_length=255, verbose_name="Nội dung đáp án"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Là đáp án đúng"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="resources.trainingquestion",
                        verbose_name="Câu hỏi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(verbose_name="Điểm số (0-100)")),
                (
                    "is_passed",
                    models.BooleanField(default=False, verbose_name="Đạt yêu cầu"),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="Số câu đúng"),
                ),
                (
                    "total_questions",
                    models.IntegerField(default=0, verbose_name="Tổng số câu"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày thi"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.productdocument",
                        verbose_name="Bài kiểm tra",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nhân viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kết quả bài thi",
                "verbose_name_plural": "Lịch sử thi",
            },
        ),
    ]
