# Generated by Django 5.2.8 on 2025-11-24 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Mới (Chưa gọi)'), ('CALLING', 'Đang chăm sóc'), ('NO_ANSWER', 'Không nghe máy'), ('WRONG_NUMBER', 'Sai số'), ('NOT_INTERESTED', 'Không có nhu cầu'), ('BOOKED', 'Đã đặt lịch hẹn')], default='NEW', max_length=50, verbose_name='Kết quả cuộc gọi')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú chi tiết')),
                ('call_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gọi')),
                ('caller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người gọi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='customers.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Lịch sử cuộc gọi',
                'verbose_name_plural': 'Quản lý Telesale',
            },
        ),
    ]
