# Generated by Django 4.2.26 on 2025-12-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telesales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('NEW', 'Mới (Chưa gọi)'), ('NO_ANSWER', 'Không nhấc máy'), ('BUSY', 'Bận'), ('WRONG_NUMBER', 'Sai số'), ('SPAM', 'Spam'), ('BOOKED', 'Đặt hẹn'), ('CONSULTING', 'Tham khảo'), ('FOLLOW_UP', 'Chăm thêm'), ('FAR_AWAY', 'Tỉnh xa')], default='NEW', max_length=50, verbose_name='Kết quả cuộc gọi'),
        ),
    ]
