# Generated by Django 5.2.8 on 2025-12-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telesales", "0002_alter_calllog_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calllog",
            options={
                "ordering": ["-call_time"],
                "verbose_name": "Lịch sử cuộc gọi",
                "verbose_name_plural": "Lịch sử cuộc gọi",
            },
        ),
        migrations.AddField(
            model_name="calllog",
            name="recall_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày chăm sóc lại"
            ),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="note",
            field=models.TextField(blank=True, verbose_name="Ghi chú"),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Data mới chưa gọi"),
                    ("BOOKED", "Đã chốt lịch hẹn"),
                    ("FAR_AWAY", "Khách ở xa / Không tiện đến"),
                    ("BUSY", "Bận / Gọi lại sau"),
                    ("WRONG_NUMBER", "Sai số / Không liên lạc được"),
                    ("SPAM", "Số rác / Khách không quan tâm"),
                    ("CONSULTING", "Đang tư vấn / Cần thêm thời gian"),
                    ("FOLLOW_UP", "Khách cũ cần theo dõi"),
                    ("RECALL", "Chăm sóc lại (Đặt lịch)"),
                ],
                default="NEW",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
