# Generated by Django 5.2.8 on 2025-12-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telesales", "0003_alter_calllog_options_calllog_recall_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calllog",
            options={
                "verbose_name": "Lịch sử cuộc gọi",
                "verbose_name_plural": "Quản lý Telesale",
            },
        ),
        migrations.RemoveField(
            model_name="calllog",
            name="recall_date",
        ),
        migrations.AlterField(
            model_name="calllog",
            name="note",
            field=models.TextField(blank=True, verbose_name="Ghi chú chi tiết"),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Mới (Chưa gọi)"),
                    ("NO_ANSWER", "Không nhấc máy"),
                    ("BUSY", "Bận"),
                    ("WRONG_NUMBER", "Sai số"),
                    ("SPAM", "Spam"),
                    ("BOOKED", "Đặt hẹn"),
                    ("CONSULTING", "Tham khảo"),
                    ("FOLLOW_UP", "Chăm thêm"),
                    ("FAR_AWAY", "Tỉnh xa"),
                ],
                default="NEW",
                max_length=50,
                verbose_name="Kết quả cuộc gọi",
            ),
        ),
    ]
