# Generated by Django 5.2.8 on 2025-12-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telesales", "0004_alter_calllog_options_remove_calllog_recall_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="callback_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Lịch hẹn gọi lại"
            ),
        ),
    ]
