# Generated by Django 5.2.8 on 2026-01-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telesales", "0005_calllog_callback_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Mới (Chưa gọi)"),
                    ("NO_ANSWER", "Không nhấc máy"),
                    ("BUSY", "Bận"),
                    ("WRONG_NUMBER", "Sai số"),
                    ("SPAM", "Spam"),
                    ("BOOKED", "Đặt hẹn"),
                    ("CONSULTING", "Tham khảo"),
                    ("FOLLOW_UP", "Chăm thêm"),
                    ("FAR_AWAY", "Tỉnh xa"),
                    ("NO_MONEY", "Không có kinh tế"),
                ],
                default="NEW",
                max_length=50,
                verbose_name="Kết quả cuộc gọi",
            ),
        ),
    ]
