# Generated by Django 4.2.26 on 2025-12-09 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên thuốc/Vật tư')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã SP (SKU)')),
                ('unit', models.CharField(max_length=50, verbose_name='Đơn vị tính')),
                ('cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá vốn')),
                ('stock', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('min_stock', models.IntegerField(default=10, verbose_name='Cảnh báo tối thiểu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả/Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm/Thuốc',
                'verbose_name_plural': 'Kho hàng',
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('IMPORT', 'Nhập kho'), ('EXPORT', 'Xuất kho/Sử dụng'), ('ADJUST', 'Kiểm kê/Điều chỉnh')], max_length=20, verbose_name='Loại GD')),
                ('quantity', models.IntegerField(verbose_name='Số lượng thay đổi')),
                ('stock_after', models.IntegerField(null=True, verbose_name='Tồn sau GD')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
