# Generated by Django 4.2.26 on 2026-07-22 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViralSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('TIKTOK', 'TikTok'), ('YOUTUBE', 'YouTube Shorts'), ('FACEBOOK', 'Facebook Reels')], max_length=10, verbose_name='Nền tảng')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tên chủ đề/dự án')),
                ('hook', models.TextField(verbose_name='Hook (3 giây đầu)')),
                ('script_content', models.TextField(verbose_name='Nội dung kịch bản')),
                ('post_caption', models.TextField(blank=True, verbose_name='Nội dung bài đăng (caption)')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chấm...'), ('DONE', 'Đã chấm xong'), ('ERROR', 'Lỗi khi chấm')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Điểm số (0-100)')),
                ('verdict', models.CharField(blank=True, max_length=300, verbose_name='Kết luận ngắn gọn')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='Điểm mạnh')),
                ('weaknesses', models.JSONField(blank=True, default=list, verbose_name='Điểm yếu')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='Gợi ý cải thiện')),
                ('platform_fit', models.TextField(blank=True, verbose_name='Nhận xét mức độ phù hợp nền tảng')),
                ('error_message', models.TextField(blank=True, verbose_name='Lỗi (nếu có)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viral_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kịch bản Viral',
                'verbose_name_plural': 'Chấm điểm Viral',
                'ordering': ['-created_at'],
            },
        ),
    ]
