# Generated by Django 4.2.26 on 2026-07-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viralsubmission',
            name='checks',
            field=models.JSONField(blank=True, default=list, verbose_name='Checklist từng tiêu chí (kiểu Yoast)'),
        ),
        migrations.AddField(
            model_name='viralsubmission',
            name='production_tips',
            field=models.JSONField(blank=True, default=list, verbose_name='Gợi ý sản xuất (hình ảnh/âm thanh/dựng phim)'),
        ),
    ]
