# Generated by Django 4.2.26 on 2026-07-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_analysis', '0002_viralsubmission_checks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viralsubmission',
            name='rewrite_examples',
            field=models.JSONField(blank=True, default=list, verbose_name='Viết lại mẫu (before/after)'),
        ),
    ]
