# Generated by Django 4.2.26 on 2026-07-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_analysis', '0003_viralsubmission_rewrite_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='viralsubmission',
            name='content_type',
            field=models.CharField(choices=[('SCRIPT', 'Kịch bản có lời thoại'), ('FORMAT', 'Bắt trend / Định dạng có sẵn (biến hình, transition, banter mượn trend...)')], default='SCRIPT', max_length=10, verbose_name='Loại nội dung'),
        ),
        migrations.AlterField(
            model_name='viralsubmission',
            name='hook',
            field=models.TextField(verbose_name='Hook (3 giây đầu) / Mô tả cảnh mở đầu'),
        ),
        migrations.AlterField(
            model_name='viralsubmission',
            name='script_content',
            field=models.TextField(verbose_name='Nội dung kịch bản / Mô tả diễn biến các cảnh'),
        ),
    ]
