# Generated by Django 5.2.8 on 2025-11-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCampaignStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True, verbose_name='Ngày báo cáo')),
                ('spend_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Ngân sách tiêu (VNĐ)')),
                ('comments', models.IntegerField(default=0, verbose_name='Số Comment')),
                ('inboxes', models.IntegerField(default=0, verbose_name='Số Inbox')),
                ('leads', models.IntegerField(default=0, verbose_name='Số điện thoại (Leads)')),
                ('appointments', models.IntegerField(default=0, verbose_name='Số lịch hẹn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Báo cáo Marketing',
                'verbose_name_plural': 'Báo cáo Marketing',
                'ordering': ['-report_date'],
            },
        ),
    ]
