# Generated by Django 5.2.8 on 2025-11-28 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên công việc')),
                ('category', models.CharField(choices=[('CONTENT', 'Viết Content'), ('DESIGN', 'Thiết kế (Designer)'), ('VIDEO', 'Quay/Dựng Video'), ('ADS', 'Chạy Ads'), ('OTHER', 'Khác')], default='CONTENT', max_length=20, verbose_name='Hạng mục')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu')),
                ('deadline', models.DateField(verbose_name='Hạn chót (Deadline)')),
                ('status', models.CharField(choices=[('TODO', 'Chưa làm'), ('DOING', 'Đang làm'), ('REVIEW', 'Chờ duyệt'), ('DONE', 'Hoàn thành')], default='TODO', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú/Yêu cầu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách (PIC)')),
            ],
            options={
                'verbose_name': 'Công việc Marketing',
                'verbose_name_plural': 'Quản lý Công việc',
                'ordering': ['deadline'],
            },
        ),
    ]
