# Generated by Django 4.2.26 on 2025-12-01 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0002_marketingtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycampaignstat',
            options={'ordering': ['-report_date', 'marketer'], 'verbose_name': 'Báo cáo Marketing', 'verbose_name_plural': 'Báo cáo Marketing'},
        ),
        migrations.AddField(
            model_name='dailycampaignstat',
            name='marketer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Người chạy Ads'),
        ),
        migrations.AddField(
            model_name='dailycampaignstat',
            name='service',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dịch vụ/Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='dailycampaignstat',
            name='report_date',
            field=models.DateField(verbose_name='Ngày báo cáo'),
        ),
        migrations.CreateModel(
            name='ContentAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên Ads (Mã)')),
                ('ad_headline', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề (Headline)')),
                ('post_content', models.TextField(blank=True, verbose_name='Nội dung bài Post')),
                ('link_video', models.URLField(blank=True, null=True, verbose_name='Link Source Video')),
                ('link_thumb', models.URLField(blank=True, null=True, verbose_name='Link Source Thumb')),
                ('result_note', models.TextField(blank=True, verbose_name='Kết quả chạy/Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('content_creator', models.ForeignKey(blank=True, limit_choices_to={'role': 'CONTENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contents', to=settings.AUTH_USER_MODEL, verbose_name='NV Content')),
                ('editor', models.ForeignKey(blank=True, limit_choices_to={'role': 'EDITOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_contents', to=settings.AUTH_USER_MODEL, verbose_name='NV Editor')),
                ('marketer', models.ForeignKey(blank=True, limit_choices_to={'role': 'MARKETING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_ads', to=settings.AUTH_USER_MODEL, verbose_name='Người chạy Ads')),
            ],
            options={
                'verbose_name': 'Content Quảng Cáo',
                'verbose_name_plural': 'Kho Content & Ads',
                'ordering': ['-created_at'],
            },
        ),
    ]
