# Generated by Django 4.2.26 on 2025-12-08 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_service_alter_order_total_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0003_alter_dailycampaignstat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentad',
            options={'verbose_name': 'Bài Content Ads', 'verbose_name_plural': 'Kho Content Quảng Cáo'},
        ),
        migrations.AlterModelOptions(
            name='dailycampaignstat',
            options={'verbose_name': 'Số liệu Ads hàng ngày', 'verbose_name_plural': 'Báo cáo Ads'},
        ),
        migrations.AlterModelOptions(
            name='marketingtask',
            options={'verbose_name': 'Công việc Marketing', 'verbose_name_plural': 'Quản lý Content & Ads'},
        ),
        migrations.RemoveField(
            model_name='contentad',
            name='link_thumb',
        ),
        migrations.RemoveField(
            model_name='contentad',
            name='link_video',
        ),
        migrations.RemoveField(
            model_name='contentad',
            name='result_note',
        ),
        migrations.RemoveField(
            model_name='marketingtask',
            name='category',
        ),
        migrations.RemoveField(
            model_name='marketingtask',
            name='note',
        ),
        migrations.RemoveField(
            model_name='marketingtask',
            name='pic',
        ),
        migrations.AddField(
            model_name='dailycampaignstat',
            name='revenue_ads',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Doanh thu từ Ads'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='budget',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Ngân sách (Tùy chọn)'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='content',
            field=models.TextField(blank=True, verbose_name='Nội dung bài viết/Ghi chú'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marketing_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo task'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='link_final',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Final (Sản phẩm)'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='link_source',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Source (Kịch bản/Raw)'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='link_thumb',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Ảnh Thumb'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='pic_ads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_ads', to=settings.AUTH_USER_MODEL, verbose_name='NV Chạy Ads'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='pic_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_content', to=settings.AUTH_USER_MODEL, verbose_name='NV Content'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='pic_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_design', to=settings.AUTH_USER_MODEL, verbose_name='NV Dựng/Thiết kế'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='platform',
            field=models.CharField(default='Facebook', max_length=50, verbose_name='Nền tảng'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.service', verbose_name='Dịch vụ quảng bá'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='ad_headline',
            field=models.CharField(max_length=200, verbose_name='Headline (Giật tít)'),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='content_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ads', to=settings.AUTH_USER_MODEL, verbose_name='Người viết'),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_ads', to=settings.AUTH_USER_MODEL, verbose_name='Editor duyệt'),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='marketer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_ads', to=settings.AUTH_USER_MODEL, verbose_name='Marketer chạy'),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='post_content',
            field=models.TextField(verbose_name='Nội dung bài viết'),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề nội bộ'),
        ),
        migrations.AlterField(
            model_name='dailycampaignstat',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='Bình luận'),
        ),
        migrations.AlterField(
            model_name='dailycampaignstat',
            name='inboxes',
            field=models.IntegerField(default=0, verbose_name='Tin nhắn (Inbox)'),
        ),
        migrations.AlterField(
            model_name='dailycampaignstat',
            name='leads',
            field=models.IntegerField(default=0, verbose_name='Số SĐT (Leads)'),
        ),
        migrations.AlterField(
            model_name='dailycampaignstat',
            name='service',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dịch vụ/Chiến dịch'),
        ),
        migrations.AlterField(
            model_name='dailycampaignstat',
            name='spend_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Chi tiêu (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='marketingtask',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='marketingtask',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='marketingtask',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Lên kế hoạch'), ('WRITING', 'Đang viết/Sản xuất'), ('DESIGNING', 'Đang thiết kế'), ('RUNNING', 'Đang chạy Ads'), ('COMPLETED', 'Hoàn thành'), ('PAUSED', 'Tạm dừng')], default='PLANNING', max_length=50, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='marketingtask',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề/Chủ đề'),
        ),
        migrations.CreateModel(
            name='TaskFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung phản hồi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='marketing.marketingtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
