# Generated by Django 5.2.8 on 2025-12-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_alter_contentad_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycampaignstat",
            name="clicks",
            field=models.IntegerField(default=0, verbose_name="Lượt nhấp (Clicks)"),
        ),
        migrations.AddField(
            model_name="dailycampaignstat",
            name="impressions",
            field=models.IntegerField(default=0, verbose_name="Lượt hiển thị (Impr)"),
        ),
        migrations.AddField(
            model_name="dailycampaignstat",
            name="platform",
            field=models.CharField(
                choices=[
                    ("FACEBOOK", "Facebook Ads"),
                    ("GOOGLE", "Google Ads"),
                    ("TIKTOK", "Tiktok Ads"),
                    ("ZALO", "Zalo Ads"),
                    ("WEBSITE", "Website/SEO"),
                    ("OTHER", "Khác"),
                ],
                default="FACEBOOK",
                max_length=20,
                verbose_name="Nền tảng",
            ),
        ),
        migrations.AddField(
            model_name="dailycampaignstat",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Lượt xem Video (Views)"),
        ),
    ]
