# Generated by Django 4.2.26 on 2025-12-01 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Tháng tính lương')),
                ('standard_work_days', models.FloatField(default=26, verbose_name='Công chuẩn')),
                ('actual_work_days', models.FloatField(default=0, verbose_name='Công thực tế')),
                ('base_salary_lock', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Lương cứng chốt')),
                ('allowance_lock', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phụ cấp chốt')),
                ('bonus', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thưởng thêm')),
                ('deduction', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phạt/Khấu trừ')),
                ('total_salary', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Thực lĩnh')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='Đã chốt sổ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Phiếu lương',
                'verbose_name_plural': 'Quản lý Bảng lương',
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Lương cứng (VNĐ)')),
                ('allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phụ cấp cố định')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu làm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Hợp đồng & Lương',
                'verbose_name_plural': 'Cấu hình Lương Nhân sự',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Mạng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú (Đi muộn/Về sớm)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Nhật ký Chấm công',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
