# Generated by Django 4.2.26 on 2025-12-08 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='note',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='is_finalized',
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=True, verbose_name='Có mặt'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='commission_rate',
            field=models.FloatField(default=0, verbose_name='% Hoa hồng (VD: 5.0)'),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tiền hoa hồng'),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='commission_rate_lock',
            field=models.FloatField(default=0, verbose_name='% Hoa hồng áp dụng'),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='sales_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Doanh số đạt được'),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='allowance_lock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phụ cấp'),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='base_salary_lock',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Lương cứng'),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='bonus',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thưởng khác'),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='total_salary',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='THỰC LĨNH'),
        ),
    ]
