# Generated by Django 5.2.8 on 2026-03-23 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_remove_attendance_check_in_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Ngày bắt đầu nghỉ")),
                ("end_date", models.DateField(verbose_name="Ngày kết thúc nghỉ")),
                ("reason", models.TextField(verbose_name="Lý do nghỉ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ duyệt"),
                            ("APPROVED", "Đã duyệt"),
                            ("REJECTED", "Từ chối"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nhân viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn nghỉ phép",
                "verbose_name_plural": "Quản lý Nghỉ phép",
            },
        ),
    ]
