# Generated by Django 5.2.8 on 2026-03-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_leaverequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("FULL", "Cả ngày"),
                    ("MORNING", "Nửa ngày (Sáng)"),
                    ("AFTERNOON", "Nửa ngày (Chiều)"),
                ],
                default="FULL",
                max_length=20,
                verbose_name="Thời lượng",
            ),
        ),
    ]
