# Generated by Django 5.2.8 on 2025-11-24 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Ngày giờ hẹn')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Đã đặt lịch'), ('ARRIVED', 'Khách đã đến'), ('IN_CONSULTATION', 'Đang tư vấn'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Hủy hẹn'), ('NO_SHOW', 'Khách không đến')], default='SCHEDULED', max_length=50, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_consultant', models.ForeignKey(blank=True, limit_choices_to={'role': 'CONSULTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Sale tư vấn')),
                ('assigned_doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ phụ trách')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customers.customer', verbose_name='Khách hàng')),
                ('receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Lễ tân check-in')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Quản lý Lịch hẹn',
            },
        ),
    ]
