# Generated by Django 5.2.8 on 2026-02-05 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_appointment_assigned_technician"),
        ("sales", "0005_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="note",
            field=models.TextField(blank=True, verbose_name="Ghi chú"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales.service",
                verbose_name="Dịch vụ / Tour",
            ),
        ),
    ]
