# Generated by Django 5.2.8 on 2026-07-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_appointment_appointment_date_index"),
        ("bookings", "0003_appointment_note_appointment_service"),
    ]

    operations = []
