# Generated by Django 5.2.8 on 2025-11-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('TELESALE', 'Nhân viên Telesale'), ('RECEPTIONIST', 'Lễ tân'), ('DOCTOR', 'Bác sĩ'), ('CONSULTANT', 'Sale Tư vấn'), ('TECHNICIAN', 'Kỹ thuật viên')], default='ADMIN', max_length=50, verbose_name='Vai trò'),
        ),
    ]
