# Generated by Django 5.2.8 on 2025-11-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('TELESALE', 'Nhân viên Telesale'), ('RECEPTIONIST', 'Lễ tân'), ('DOCTOR', 'Bác sĩ'), ('CONSULTANT', 'Sale Tư vấn'), ('TECHNICIAN', 'Kỹ thuật viên'), ('MARKETING', 'Nhân viên Marketing')], default='ADMIN', max_length=50, verbose_name='Vai trò'),
        ),
    ]
