# Generated by Django 4.2.26 on 2025-12-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('TELESALE', 'Nhân viên Telesale'), ('RECEPTIONIST', 'Lễ tân'), ('DOCTOR', 'Bác sĩ'), ('CONSULTANT', 'Sale Tư vấn'), ('TECHNICIAN', 'Kỹ thuật viên'), ('MARKETING', 'Marketing (Chạy Ads)'), ('CONTENT', 'Nhân viên Content'), ('EDITOR', 'Nhân viên Editor'), ('DESIGNER', 'Nhân viên Thiết kế')], default='ADMIN', max_length=50, verbose_name='Vai trò'),
        ),
    ]
