# Generated by Django 5.2.8 on 2025-12-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.CharField(
                blank=True,
                choices=[("TEAM_A", "Team A"), ("TEAM_B", "Team B")],
                max_length=20,
                null=True,
                verbose_name="Nhóm Telesale",
            ),
        ),
    ]
