# Generated by Django 5.2.8 on 2026-01-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowed_menus",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Menu được phép truy cập"
            ),
        ),
    ]
