# Generated by Django 5.2.8 on 2026-02-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_user_allowed_menus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="allowed_menus",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Quyền truy cập Menu"
            ),
        ),
    ]
